# Development environment configuration that extends the base docker-compose.yml
services:
  # Backend API service (development mode)
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - .:/app
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    command: ["uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Frontend UI service (development mode)
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - OLLAMA_API_URL=http://ollama:11434
      - ML_SERVICE_URL=http://ml-service:5000
    command: ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]

  # ML service (development mode)
  ml-service:
    build:
      context: .
      dockerfile: docker/ml/Dockerfile
    volumes:
      - .:/app
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - FLASK_APP=ml.app
      - FLASK_ENV=development
    command: ["python", "ml/app.py"]
  
  # Development tools and utilities
  jupyter:
    build:
      context: .
      dockerfile: docker/ml/Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ./notebooks:/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--notebook-dir=/notebooks"]
    networks:
      - codexcontinue-network